name: Server Lint & Tests

env:
  NODE_VERSION: 16.13.0
  YARN_VERSION: 1.22.4

on:
  push:
    branches:
      - '**'
  release:
    types:
      - published

jobs:
  linter-and-tests:
    name: Run linter & tests
    runs-on: ubuntu-latest

    defaults:

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: |
            '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: |
          yarn policies set-version ${{ env.YARN_VERSION }}
          yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
